// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/avored/go-ecommerce/ent/order"
	"github.com/avored/go-ecommerce/ent/orderproduct"
	"github.com/avored/go-ecommerce/ent/predicate"
	"github.com/avored/go-ecommerce/ent/product"
)

// OrderProductUpdate is the builder for updating OrderProduct entities.
type OrderProductUpdate struct {
	config
	hooks    []Hook
	mutation *OrderProductMutation
}

// Where appends a list predicates to the OrderProductUpdate builder.
func (opu *OrderProductUpdate) Where(ps ...predicate.OrderProduct) *OrderProductUpdate {
	opu.mutation.Where(ps...)
	return opu
}

// SetUpdatedAt sets the "updated_at" field.
func (opu *OrderProductUpdate) SetUpdatedAt(t time.Time) *OrderProductUpdate {
	opu.mutation.SetUpdatedAt(t)
	return opu
}

// SetOrderID sets the "order_id" field.
func (opu *OrderProductUpdate) SetOrderID(i int) *OrderProductUpdate {
	opu.mutation.SetOrderID(i)
	return opu
}

// SetNillableOrderID sets the "order_id" field if the given value is not nil.
func (opu *OrderProductUpdate) SetNillableOrderID(i *int) *OrderProductUpdate {
	if i != nil {
		opu.SetOrderID(*i)
	}
	return opu
}

// ClearOrderID clears the value of the "order_id" field.
func (opu *OrderProductUpdate) ClearOrderID() *OrderProductUpdate {
	opu.mutation.ClearOrderID()
	return opu
}

// SetProductID sets the "product_id" field.
func (opu *OrderProductUpdate) SetProductID(i int) *OrderProductUpdate {
	opu.mutation.SetProductID(i)
	return opu
}

// SetNillableProductID sets the "product_id" field if the given value is not nil.
func (opu *OrderProductUpdate) SetNillableProductID(i *int) *OrderProductUpdate {
	if i != nil {
		opu.SetProductID(*i)
	}
	return opu
}

// ClearProductID clears the value of the "product_id" field.
func (opu *OrderProductUpdate) ClearProductID() *OrderProductUpdate {
	opu.mutation.ClearProductID()
	return opu
}

// SetQty sets the "qty" field.
func (opu *OrderProductUpdate) SetQty(f float64) *OrderProductUpdate {
	opu.mutation.ResetQty()
	opu.mutation.SetQty(f)
	return opu
}

// AddQty adds f to the "qty" field.
func (opu *OrderProductUpdate) AddQty(f float64) *OrderProductUpdate {
	opu.mutation.AddQty(f)
	return opu
}

// SetAmount sets the "amount" field.
func (opu *OrderProductUpdate) SetAmount(f float64) *OrderProductUpdate {
	opu.mutation.ResetAmount()
	opu.mutation.SetAmount(f)
	return opu
}

// AddAmount adds f to the "amount" field.
func (opu *OrderProductUpdate) AddAmount(f float64) *OrderProductUpdate {
	opu.mutation.AddAmount(f)
	return opu
}

// SetOrderProductOrderID sets the "order_product_order" edge to the Order entity by ID.
func (opu *OrderProductUpdate) SetOrderProductOrderID(id int) *OrderProductUpdate {
	opu.mutation.SetOrderProductOrderID(id)
	return opu
}

// SetNillableOrderProductOrderID sets the "order_product_order" edge to the Order entity by ID if the given value is not nil.
func (opu *OrderProductUpdate) SetNillableOrderProductOrderID(id *int) *OrderProductUpdate {
	if id != nil {
		opu = opu.SetOrderProductOrderID(*id)
	}
	return opu
}

// SetOrderProductOrder sets the "order_product_order" edge to the Order entity.
func (opu *OrderProductUpdate) SetOrderProductOrder(o *Order) *OrderProductUpdate {
	return opu.SetOrderProductOrderID(o.ID)
}

// SetOrderProductProductID sets the "order_product_product" edge to the Product entity by ID.
func (opu *OrderProductUpdate) SetOrderProductProductID(id int) *OrderProductUpdate {
	opu.mutation.SetOrderProductProductID(id)
	return opu
}

// SetNillableOrderProductProductID sets the "order_product_product" edge to the Product entity by ID if the given value is not nil.
func (opu *OrderProductUpdate) SetNillableOrderProductProductID(id *int) *OrderProductUpdate {
	if id != nil {
		opu = opu.SetOrderProductProductID(*id)
	}
	return opu
}

// SetOrderProductProduct sets the "order_product_product" edge to the Product entity.
func (opu *OrderProductUpdate) SetOrderProductProduct(p *Product) *OrderProductUpdate {
	return opu.SetOrderProductProductID(p.ID)
}

// Mutation returns the OrderProductMutation object of the builder.
func (opu *OrderProductUpdate) Mutation() *OrderProductMutation {
	return opu.mutation
}

// ClearOrderProductOrder clears the "order_product_order" edge to the Order entity.
func (opu *OrderProductUpdate) ClearOrderProductOrder() *OrderProductUpdate {
	opu.mutation.ClearOrderProductOrder()
	return opu
}

// ClearOrderProductProduct clears the "order_product_product" edge to the Product entity.
func (opu *OrderProductUpdate) ClearOrderProductProduct() *OrderProductUpdate {
	opu.mutation.ClearOrderProductProduct()
	return opu
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (opu *OrderProductUpdate) Save(ctx context.Context) (int, error) {
	var (
		err      error
		affected int
	)
	opu.defaults()
	if len(opu.hooks) == 0 {
		affected, err = opu.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*OrderProductMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			opu.mutation = mutation
			affected, err = opu.sqlSave(ctx)
			mutation.done = true
			return affected, err
		})
		for i := len(opu.hooks) - 1; i >= 0; i-- {
			if opu.hooks[i] == nil {
				return 0, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = opu.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, opu.mutation); err != nil {
			return 0, err
		}
	}
	return affected, err
}

// SaveX is like Save, but panics if an error occurs.
func (opu *OrderProductUpdate) SaveX(ctx context.Context) int {
	affected, err := opu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (opu *OrderProductUpdate) Exec(ctx context.Context) error {
	_, err := opu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (opu *OrderProductUpdate) ExecX(ctx context.Context) {
	if err := opu.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (opu *OrderProductUpdate) defaults() {
	if _, ok := opu.mutation.UpdatedAt(); !ok {
		v := orderproduct.UpdateDefaultUpdatedAt()
		opu.mutation.SetUpdatedAt(v)
	}
}

func (opu *OrderProductUpdate) sqlSave(ctx context.Context) (n int, err error) {
	_spec := &sqlgraph.UpdateSpec{
		Node: &sqlgraph.NodeSpec{
			Table:   orderproduct.Table,
			Columns: orderproduct.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: orderproduct.FieldID,
			},
		},
	}
	if ps := opu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := opu.mutation.UpdatedAt(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeTime,
			Value:  value,
			Column: orderproduct.FieldUpdatedAt,
		})
	}
	if value, ok := opu.mutation.Qty(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeFloat64,
			Value:  value,
			Column: orderproduct.FieldQty,
		})
	}
	if value, ok := opu.mutation.AddedQty(); ok {
		_spec.Fields.Add = append(_spec.Fields.Add, &sqlgraph.FieldSpec{
			Type:   field.TypeFloat64,
			Value:  value,
			Column: orderproduct.FieldQty,
		})
	}
	if value, ok := opu.mutation.Amount(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeFloat64,
			Value:  value,
			Column: orderproduct.FieldAmount,
		})
	}
	if value, ok := opu.mutation.AddedAmount(); ok {
		_spec.Fields.Add = append(_spec.Fields.Add, &sqlgraph.FieldSpec{
			Type:   field.TypeFloat64,
			Value:  value,
			Column: orderproduct.FieldAmount,
		})
	}
	if opu.mutation.OrderProductOrderCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   orderproduct.OrderProductOrderTable,
			Columns: []string{orderproduct.OrderProductOrderColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: order.FieldID,
				},
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := opu.mutation.OrderProductOrderIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   orderproduct.OrderProductOrderTable,
			Columns: []string{orderproduct.OrderProductOrderColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: order.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if opu.mutation.OrderProductProductCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   orderproduct.OrderProductProductTable,
			Columns: []string{orderproduct.OrderProductProductColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: product.FieldID,
				},
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := opu.mutation.OrderProductProductIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   orderproduct.OrderProductProductTable,
			Columns: []string{orderproduct.OrderProductProductColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: product.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, opu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{orderproduct.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{err.Error(), err}
		}
		return 0, err
	}
	return n, nil
}

// OrderProductUpdateOne is the builder for updating a single OrderProduct entity.
type OrderProductUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *OrderProductMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (opuo *OrderProductUpdateOne) SetUpdatedAt(t time.Time) *OrderProductUpdateOne {
	opuo.mutation.SetUpdatedAt(t)
	return opuo
}

// SetOrderID sets the "order_id" field.
func (opuo *OrderProductUpdateOne) SetOrderID(i int) *OrderProductUpdateOne {
	opuo.mutation.SetOrderID(i)
	return opuo
}

// SetNillableOrderID sets the "order_id" field if the given value is not nil.
func (opuo *OrderProductUpdateOne) SetNillableOrderID(i *int) *OrderProductUpdateOne {
	if i != nil {
		opuo.SetOrderID(*i)
	}
	return opuo
}

// ClearOrderID clears the value of the "order_id" field.
func (opuo *OrderProductUpdateOne) ClearOrderID() *OrderProductUpdateOne {
	opuo.mutation.ClearOrderID()
	return opuo
}

// SetProductID sets the "product_id" field.
func (opuo *OrderProductUpdateOne) SetProductID(i int) *OrderProductUpdateOne {
	opuo.mutation.SetProductID(i)
	return opuo
}

// SetNillableProductID sets the "product_id" field if the given value is not nil.
func (opuo *OrderProductUpdateOne) SetNillableProductID(i *int) *OrderProductUpdateOne {
	if i != nil {
		opuo.SetProductID(*i)
	}
	return opuo
}

// ClearProductID clears the value of the "product_id" field.
func (opuo *OrderProductUpdateOne) ClearProductID() *OrderProductUpdateOne {
	opuo.mutation.ClearProductID()
	return opuo
}

// SetQty sets the "qty" field.
func (opuo *OrderProductUpdateOne) SetQty(f float64) *OrderProductUpdateOne {
	opuo.mutation.ResetQty()
	opuo.mutation.SetQty(f)
	return opuo
}

// AddQty adds f to the "qty" field.
func (opuo *OrderProductUpdateOne) AddQty(f float64) *OrderProductUpdateOne {
	opuo.mutation.AddQty(f)
	return opuo
}

// SetAmount sets the "amount" field.
func (opuo *OrderProductUpdateOne) SetAmount(f float64) *OrderProductUpdateOne {
	opuo.mutation.ResetAmount()
	opuo.mutation.SetAmount(f)
	return opuo
}

// AddAmount adds f to the "amount" field.
func (opuo *OrderProductUpdateOne) AddAmount(f float64) *OrderProductUpdateOne {
	opuo.mutation.AddAmount(f)
	return opuo
}

// SetOrderProductOrderID sets the "order_product_order" edge to the Order entity by ID.
func (opuo *OrderProductUpdateOne) SetOrderProductOrderID(id int) *OrderProductUpdateOne {
	opuo.mutation.SetOrderProductOrderID(id)
	return opuo
}

// SetNillableOrderProductOrderID sets the "order_product_order" edge to the Order entity by ID if the given value is not nil.
func (opuo *OrderProductUpdateOne) SetNillableOrderProductOrderID(id *int) *OrderProductUpdateOne {
	if id != nil {
		opuo = opuo.SetOrderProductOrderID(*id)
	}
	return opuo
}

// SetOrderProductOrder sets the "order_product_order" edge to the Order entity.
func (opuo *OrderProductUpdateOne) SetOrderProductOrder(o *Order) *OrderProductUpdateOne {
	return opuo.SetOrderProductOrderID(o.ID)
}

// SetOrderProductProductID sets the "order_product_product" edge to the Product entity by ID.
func (opuo *OrderProductUpdateOne) SetOrderProductProductID(id int) *OrderProductUpdateOne {
	opuo.mutation.SetOrderProductProductID(id)
	return opuo
}

// SetNillableOrderProductProductID sets the "order_product_product" edge to the Product entity by ID if the given value is not nil.
func (opuo *OrderProductUpdateOne) SetNillableOrderProductProductID(id *int) *OrderProductUpdateOne {
	if id != nil {
		opuo = opuo.SetOrderProductProductID(*id)
	}
	return opuo
}

// SetOrderProductProduct sets the "order_product_product" edge to the Product entity.
func (opuo *OrderProductUpdateOne) SetOrderProductProduct(p *Product) *OrderProductUpdateOne {
	return opuo.SetOrderProductProductID(p.ID)
}

// Mutation returns the OrderProductMutation object of the builder.
func (opuo *OrderProductUpdateOne) Mutation() *OrderProductMutation {
	return opuo.mutation
}

// ClearOrderProductOrder clears the "order_product_order" edge to the Order entity.
func (opuo *OrderProductUpdateOne) ClearOrderProductOrder() *OrderProductUpdateOne {
	opuo.mutation.ClearOrderProductOrder()
	return opuo
}

// ClearOrderProductProduct clears the "order_product_product" edge to the Product entity.
func (opuo *OrderProductUpdateOne) ClearOrderProductProduct() *OrderProductUpdateOne {
	opuo.mutation.ClearOrderProductProduct()
	return opuo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (opuo *OrderProductUpdateOne) Select(field string, fields ...string) *OrderProductUpdateOne {
	opuo.fields = append([]string{field}, fields...)
	return opuo
}

// Save executes the query and returns the updated OrderProduct entity.
func (opuo *OrderProductUpdateOne) Save(ctx context.Context) (*OrderProduct, error) {
	var (
		err  error
		node *OrderProduct
	)
	opuo.defaults()
	if len(opuo.hooks) == 0 {
		node, err = opuo.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*OrderProductMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			opuo.mutation = mutation
			node, err = opuo.sqlSave(ctx)
			mutation.done = true
			return node, err
		})
		for i := len(opuo.hooks) - 1; i >= 0; i-- {
			if opuo.hooks[i] == nil {
				return nil, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = opuo.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, opuo.mutation); err != nil {
			return nil, err
		}
	}
	return node, err
}

// SaveX is like Save, but panics if an error occurs.
func (opuo *OrderProductUpdateOne) SaveX(ctx context.Context) *OrderProduct {
	node, err := opuo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (opuo *OrderProductUpdateOne) Exec(ctx context.Context) error {
	_, err := opuo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (opuo *OrderProductUpdateOne) ExecX(ctx context.Context) {
	if err := opuo.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (opuo *OrderProductUpdateOne) defaults() {
	if _, ok := opuo.mutation.UpdatedAt(); !ok {
		v := orderproduct.UpdateDefaultUpdatedAt()
		opuo.mutation.SetUpdatedAt(v)
	}
}

func (opuo *OrderProductUpdateOne) sqlSave(ctx context.Context) (_node *OrderProduct, err error) {
	_spec := &sqlgraph.UpdateSpec{
		Node: &sqlgraph.NodeSpec{
			Table:   orderproduct.Table,
			Columns: orderproduct.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: orderproduct.FieldID,
			},
		},
	}
	id, ok := opuo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "OrderProduct.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := opuo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, orderproduct.FieldID)
		for _, f := range fields {
			if !orderproduct.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != orderproduct.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := opuo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := opuo.mutation.UpdatedAt(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeTime,
			Value:  value,
			Column: orderproduct.FieldUpdatedAt,
		})
	}
	if value, ok := opuo.mutation.Qty(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeFloat64,
			Value:  value,
			Column: orderproduct.FieldQty,
		})
	}
	if value, ok := opuo.mutation.AddedQty(); ok {
		_spec.Fields.Add = append(_spec.Fields.Add, &sqlgraph.FieldSpec{
			Type:   field.TypeFloat64,
			Value:  value,
			Column: orderproduct.FieldQty,
		})
	}
	if value, ok := opuo.mutation.Amount(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeFloat64,
			Value:  value,
			Column: orderproduct.FieldAmount,
		})
	}
	if value, ok := opuo.mutation.AddedAmount(); ok {
		_spec.Fields.Add = append(_spec.Fields.Add, &sqlgraph.FieldSpec{
			Type:   field.TypeFloat64,
			Value:  value,
			Column: orderproduct.FieldAmount,
		})
	}
	if opuo.mutation.OrderProductOrderCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   orderproduct.OrderProductOrderTable,
			Columns: []string{orderproduct.OrderProductOrderColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: order.FieldID,
				},
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := opuo.mutation.OrderProductOrderIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   orderproduct.OrderProductOrderTable,
			Columns: []string{orderproduct.OrderProductOrderColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: order.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if opuo.mutation.OrderProductProductCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   orderproduct.OrderProductProductTable,
			Columns: []string{orderproduct.OrderProductProductColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: product.FieldID,
				},
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := opuo.mutation.OrderProductProductIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   orderproduct.OrderProductProductTable,
			Columns: []string{orderproduct.OrderProductProductColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: product.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &OrderProduct{config: opuo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, opuo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{orderproduct.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{err.Error(), err}
		}
		return nil, err
	}
	return _node, nil
}
