// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/avored/go-ecommerce/ent/order"
	"github.com/avored/go-ecommerce/ent/orderproduct"
	"github.com/avored/go-ecommerce/ent/product"
)

// OrderProductCreate is the builder for creating a OrderProduct entity.
type OrderProductCreate struct {
	config
	mutation *OrderProductMutation
	hooks    []Hook
}

// SetCreatedAt sets the "created_at" field.
func (opc *OrderProductCreate) SetCreatedAt(t time.Time) *OrderProductCreate {
	opc.mutation.SetCreatedAt(t)
	return opc
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (opc *OrderProductCreate) SetNillableCreatedAt(t *time.Time) *OrderProductCreate {
	if t != nil {
		opc.SetCreatedAt(*t)
	}
	return opc
}

// SetUpdatedAt sets the "updated_at" field.
func (opc *OrderProductCreate) SetUpdatedAt(t time.Time) *OrderProductCreate {
	opc.mutation.SetUpdatedAt(t)
	return opc
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (opc *OrderProductCreate) SetNillableUpdatedAt(t *time.Time) *OrderProductCreate {
	if t != nil {
		opc.SetUpdatedAt(*t)
	}
	return opc
}

// SetOrderID sets the "order_id" field.
func (opc *OrderProductCreate) SetOrderID(i int) *OrderProductCreate {
	opc.mutation.SetOrderID(i)
	return opc
}

// SetNillableOrderID sets the "order_id" field if the given value is not nil.
func (opc *OrderProductCreate) SetNillableOrderID(i *int) *OrderProductCreate {
	if i != nil {
		opc.SetOrderID(*i)
	}
	return opc
}

// SetProductID sets the "product_id" field.
func (opc *OrderProductCreate) SetProductID(i int) *OrderProductCreate {
	opc.mutation.SetProductID(i)
	return opc
}

// SetNillableProductID sets the "product_id" field if the given value is not nil.
func (opc *OrderProductCreate) SetNillableProductID(i *int) *OrderProductCreate {
	if i != nil {
		opc.SetProductID(*i)
	}
	return opc
}

// SetQty sets the "qty" field.
func (opc *OrderProductCreate) SetQty(f float64) *OrderProductCreate {
	opc.mutation.SetQty(f)
	return opc
}

// SetAmount sets the "amount" field.
func (opc *OrderProductCreate) SetAmount(f float64) *OrderProductCreate {
	opc.mutation.SetAmount(f)
	return opc
}

// SetOrderProductOrderID sets the "order_product_order" edge to the Order entity by ID.
func (opc *OrderProductCreate) SetOrderProductOrderID(id int) *OrderProductCreate {
	opc.mutation.SetOrderProductOrderID(id)
	return opc
}

// SetNillableOrderProductOrderID sets the "order_product_order" edge to the Order entity by ID if the given value is not nil.
func (opc *OrderProductCreate) SetNillableOrderProductOrderID(id *int) *OrderProductCreate {
	if id != nil {
		opc = opc.SetOrderProductOrderID(*id)
	}
	return opc
}

// SetOrderProductOrder sets the "order_product_order" edge to the Order entity.
func (opc *OrderProductCreate) SetOrderProductOrder(o *Order) *OrderProductCreate {
	return opc.SetOrderProductOrderID(o.ID)
}

// SetOrderProductProductID sets the "order_product_product" edge to the Product entity by ID.
func (opc *OrderProductCreate) SetOrderProductProductID(id int) *OrderProductCreate {
	opc.mutation.SetOrderProductProductID(id)
	return opc
}

// SetNillableOrderProductProductID sets the "order_product_product" edge to the Product entity by ID if the given value is not nil.
func (opc *OrderProductCreate) SetNillableOrderProductProductID(id *int) *OrderProductCreate {
	if id != nil {
		opc = opc.SetOrderProductProductID(*id)
	}
	return opc
}

// SetOrderProductProduct sets the "order_product_product" edge to the Product entity.
func (opc *OrderProductCreate) SetOrderProductProduct(p *Product) *OrderProductCreate {
	return opc.SetOrderProductProductID(p.ID)
}

// Mutation returns the OrderProductMutation object of the builder.
func (opc *OrderProductCreate) Mutation() *OrderProductMutation {
	return opc.mutation
}

// Save creates the OrderProduct in the database.
func (opc *OrderProductCreate) Save(ctx context.Context) (*OrderProduct, error) {
	var (
		err  error
		node *OrderProduct
	)
	opc.defaults()
	if len(opc.hooks) == 0 {
		if err = opc.check(); err != nil {
			return nil, err
		}
		node, err = opc.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*OrderProductMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			if err = opc.check(); err != nil {
				return nil, err
			}
			opc.mutation = mutation
			if node, err = opc.sqlSave(ctx); err != nil {
				return nil, err
			}
			mutation.id = &node.ID
			mutation.done = true
			return node, err
		})
		for i := len(opc.hooks) - 1; i >= 0; i-- {
			if opc.hooks[i] == nil {
				return nil, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = opc.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, opc.mutation); err != nil {
			return nil, err
		}
	}
	return node, err
}

// SaveX calls Save and panics if Save returns an error.
func (opc *OrderProductCreate) SaveX(ctx context.Context) *OrderProduct {
	v, err := opc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (opc *OrderProductCreate) Exec(ctx context.Context) error {
	_, err := opc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (opc *OrderProductCreate) ExecX(ctx context.Context) {
	if err := opc.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (opc *OrderProductCreate) defaults() {
	if _, ok := opc.mutation.CreatedAt(); !ok {
		v := orderproduct.DefaultCreatedAt()
		opc.mutation.SetCreatedAt(v)
	}
	if _, ok := opc.mutation.UpdatedAt(); !ok {
		v := orderproduct.DefaultUpdatedAt()
		opc.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (opc *OrderProductCreate) check() error {
	if _, ok := opc.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "OrderProduct.created_at"`)}
	}
	if _, ok := opc.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "OrderProduct.updated_at"`)}
	}
	if _, ok := opc.mutation.Qty(); !ok {
		return &ValidationError{Name: "qty", err: errors.New(`ent: missing required field "OrderProduct.qty"`)}
	}
	if _, ok := opc.mutation.Amount(); !ok {
		return &ValidationError{Name: "amount", err: errors.New(`ent: missing required field "OrderProduct.amount"`)}
	}
	return nil
}

func (opc *OrderProductCreate) sqlSave(ctx context.Context) (*OrderProduct, error) {
	_node, _spec := opc.createSpec()
	if err := sqlgraph.CreateNode(ctx, opc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{err.Error(), err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	return _node, nil
}

func (opc *OrderProductCreate) createSpec() (*OrderProduct, *sqlgraph.CreateSpec) {
	var (
		_node = &OrderProduct{config: opc.config}
		_spec = &sqlgraph.CreateSpec{
			Table: orderproduct.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: orderproduct.FieldID,
			},
		}
	)
	if value, ok := opc.mutation.CreatedAt(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeTime,
			Value:  value,
			Column: orderproduct.FieldCreatedAt,
		})
		_node.CreatedAt = value
	}
	if value, ok := opc.mutation.UpdatedAt(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeTime,
			Value:  value,
			Column: orderproduct.FieldUpdatedAt,
		})
		_node.UpdatedAt = value
	}
	if value, ok := opc.mutation.Qty(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeFloat64,
			Value:  value,
			Column: orderproduct.FieldQty,
		})
		_node.Qty = value
	}
	if value, ok := opc.mutation.Amount(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeFloat64,
			Value:  value,
			Column: orderproduct.FieldAmount,
		})
		_node.Amount = value
	}
	if nodes := opc.mutation.OrderProductOrderIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   orderproduct.OrderProductOrderTable,
			Columns: []string{orderproduct.OrderProductOrderColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: order.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.OrderID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := opc.mutation.OrderProductProductIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   orderproduct.OrderProductProductTable,
			Columns: []string{orderproduct.OrderProductProductColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: product.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.ProductID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OrderProductCreateBulk is the builder for creating many OrderProduct entities in bulk.
type OrderProductCreateBulk struct {
	config
	builders []*OrderProductCreate
}

// Save creates the OrderProduct entities in the database.
func (opcb *OrderProductCreateBulk) Save(ctx context.Context) ([]*OrderProduct, error) {
	specs := make([]*sqlgraph.CreateSpec, len(opcb.builders))
	nodes := make([]*OrderProduct, len(opcb.builders))
	mutators := make([]Mutator, len(opcb.builders))
	for i := range opcb.builders {
		func(i int, root context.Context) {
			builder := opcb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*OrderProductMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				nodes[i], specs[i] = builder.createSpec()
				var err error
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, opcb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, opcb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{err.Error(), err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, opcb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (opcb *OrderProductCreateBulk) SaveX(ctx context.Context) []*OrderProduct {
	v, err := opcb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (opcb *OrderProductCreateBulk) Exec(ctx context.Context) error {
	_, err := opcb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (opcb *OrderProductCreateBulk) ExecX(ctx context.Context) {
	if err := opcb.Exec(ctx); err != nil {
		panic(err)
	}
}
